INSERT INTO ROLE (ID, LIBELLE) VALUES
(1, 'Etudiant'),
(2, 'Professeur'),
(3, 'Gestionnaire'),
(4, 'Administrateur');

INSERT INTO PERSONNE (ID, IDENTIFIANT, NOM, PRENOM, ID_ROLE) VALUES
(1, 'dupuis4u', 'Dupuis', 'Louis', 2);

INSERT INTO FORMATION (ID, LIBELLE) VALUES
(1, 'Master 2 MIAGE SID');

INSERT INTO BATIMENT (ID, NOM, ADRESSE) VALUES
(1, 'Pôle Herbet Simon', '13 Rue Michel Ney, 54000 Nancy');

INSERT INTO COURS (ID, LIBELLE, ID_FORMATION, ID_PERSONNE_PROFESSEUR) VALUES
(1, 'Patrons de conception', 1, 1);

INSERT INTO SALLE (ID, NUMERO, ID_BATIMENT) VALUES
(1, 214, 1);

INSERT INTO SEANCE (ID, DATE_DEBUT, DATE_FIN, ID_COURS, ID_SALLE) VALUES
(1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 1),
(2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 1),
(3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 1),
(4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 1);