INSERT INTO SEANCE (ID, DATE_DEBUT, DATE_FIN) VALUES
(1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());